### ISSUE TITLE
Read all user info  Bad start tag

### ISSUE THREAD

**Issue by biencuong** [adrobinoga/pyzatt#6] opened 2018-12-17 04:58 UTC
adti@pi222:/home/pyzatt/tests$ python3 test_access.py
#############################################
     TEST OF ACCESS FUNCTIONS
 1.Read all user info
Bad start tag

**Comment by adrobinoga** [comment] 2020-03-09 05:06
This is a duplicate of #4

**Closed by adrobinoga** 2020-03-09 05:06 UTC
