### ISSUE TITLE
Read attendance log: I am testing a WL10 with the following error:

### ISSUE THREAD

**Issue by biencuong** [adrobinoga/pyzatt#5] opened 2018-12-16 19:12 UTC
I am testing a WL10,  Firmware: Ver 6.60 Sep 18 2016, with the following error:
Bad start tag
Traceback (most recent call last):
  File "test_data_record.py", line 36, in <module>
    z.read_att_log()
  File "/home/adti/.local/lib/python3.6/site-packages/PyZatt-1.0-py3.6.egg/pyzk/zkmodules/data_record.py", line 30, in read_att_log
struct.error: unpack requires a buffer of 2 bytes

**Comment by adrobinoga** [comment] 2020-03-09 05:07
This is a duplicate of #4

**Closed by adrobinoga** 2020-03-09 05:07 UTC
